---
###########################
# global variables
###########################

#Package updating
package_simulate: N/A
update: False

#Restart?
check_reboot: False
reboot_required: no

#time calculation
hour: 00
minute: 00
second: 00
time: 00

restart_msg: " A restart is not required at this time."

# Points to the default email list that is used in all playbooks
default_list: ../mail_lists/default_list.txt

# This is the main email list
main_list: 
