---
# Gives the SSH security group permission to this remote machine
- name: Permit Active Directory group SSH access
  shell: realm permit -g {{ ssh_group }}

- name: restart ssd service
  service:
    name: sssd
    state: restarted

# Gives both Ansible and the SUDOERS security group administrative permission on the remote machine
- name: Permit Active Directory group for customer sudo access
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '%{{ sudo_group }} ALL=(ALL:ALL) ALL'
    validate: /usr/sbin/visudo -cf %s

# This gives ONLY the ansible security group sudo access WITHOUT using a password
- name: Permit Active Directory group for Ansible sudo access
  lineinfile:
    path: /etc/sudoers
    state: present
    line: '%{{ ansible_group }} ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: /usr/sbin/visudo -cf %s

