---
#####################################################################################
# This playbook's function is to restrict SSH connection to only approved IP addresses/ranges
#
#Last updated by: Ben Firestine 06/23/2021
#####################################################################################

# Filter out offline hosts
- name: identify reachable hosts
  hosts: all
  gather_facts: false

  vars_files:
    - ./vars/default.yml

# Checking for online hosts
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for:
            port:"{{ ssh_port }}"
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "reachable" group
          group_by:
            key: "reachable"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

# SSH Restriction
- name: Online hosts
  hosts: reachable
  become: true
  any_errors_fatal: true
  gather_facts: True

# Import variable/secret files
  vars_files:
   # - ../secrets/vault
    - ./vars/default.yml

  tasks:

  # Installs the firewalld package on the remote machine
  - include: ./tasks/firewall_install.yml

  # Limits SSH connections on the firewall level
  - include: ./tasks/vpn_firewall.yml

  # Limits SSH connections with the sshd host files
  - include: ./tasks/vpn_ssh.yml
    when: ansible_distribution == "Ubuntu"
  
  # Emails results. UNCOMMENT OUT TO ENABLE MAIL FUNCTION
  #- include: ./tasks/mail.yml
