---
# Creates initial spreadsheet, runs compliant modules, collects data for reporting
- name: Creating excel spreadsheet
  file:
    path: "{{ excel_loc }}"
    state: touch
  delegate_to: localhost

- name: Adding initial line to spreadsheet
  lineinfile:
    insertafter: EOF
    dest: "{{ excel_loc }}"
    line: Hostname,Non-Approved Users,System Update Status,Firewall Status
  delegate_to: localhost

# Check for compliance
- include: ./local_user_check.yml
- include: ./system_status_check.yml
- include: ./firewall_check.yml

# Add collected data
- name: Editing the csv with all the compliance data gathered
  lineinfile:
    dest: "{{ excel_loc }}"
    line: "{{ ansible_hostname }},{{ item }},{{ system_status_result }},{{ firewall_results }}"
  with_items: "{{ non_approved_users }}"
  delegate_to: localhost
