---
# Local users?
- name: Get a list of local users
  shell: 'cut -d : -f 1 /etc/passwd'
  args:
    warn: false
  ignore_errors: true
  register: local_users

# Records non-approved users
- set_fact:
    non_approved_users: "{{ local_users.stdout_lines | difference(approved_users) }}"
    issue_count: "{{ issue_count | int + 1 }}"
  when: "{{ local_users.stdout | difference(approved_users) | length  }} > 0"
