---
#####################################################################################
# This playbook's function is to bind a new Linux based computer to Active Directory
#
#Last updated by: Ben Firestine 10/16/2020
#####################################################################################

# Filter out offline hosts
- name: identify reachable hosts
  hosts: all
  gather_facts: false

# Checking for online hosts
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "reachable" group
          group_by:
            key: "reachable"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

# AD Binding
- name: Online hosts
  hosts: reachable
  become: true
  any_errors_fatal: true
  gather_facts: True

# Import variable/secret files
  vars_files:
    # This contains secrets for credentials like emails
    - ../secrets/vault
    - ./vars/default.yml
 
  tasks:

  # Runs initial setup
  - include: ./tasks/initial-config.yml

  # Binds the computer to AD
  - include: ./tasks/bind.yml

  # Restricts SSH and SUDO access
  - include: ./tasks/ssh_sudo_access.yml

  - include: ./tasks/mail.yml
