---
###############################
# global variables
###############################

# Current date
date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

# Excel location
excel_loc: /tmp/{{ date }}-compliance_check.csv

# Total issues discovered
issue_count: 0

# How many computers were checked
computers_checked: 0

# Location of the default email list
default_list: ../mail_lists/default_list.txt

# Users to be emailed
main_list: 

###############################
# system_update_check variables
###############################

system_status_result: Out of Date
compliance_date: N/A
last_update: N/A

###############################
# local_user_check variables
###############################

local_users: N/A
non_approved_users: N/A
approved_users: "{{ lookup('file','./templates/approved_users.txt').splitlines() }}"


###############################
# firewall_check variables
###############################

remote_firewall_rules: N/A
approved_firewall_rules: ./templates/default_restrictions.txt
firewall_results: Configuration Mismatch
