---
###########################
# global variables
###########################

# Location of default email list	
default_list: ../mail_lists/default_list.txt

# This is the main email list
mail_list:

#custom port value
ssh_port: 22
