---
#######################
# PREPARE MAIL LIST
#######################

# List from default mail file
-  set_fact:
     default_list: "{{ lookup('file', '{{ default_list }}').splitlines() }}"

# Creates a list variable from the contents of the custom mail file ONLY when it is defined
- set_fact:
     custom_list: "{{ lookup('file', '{{ custom_list }}').splitlines() }}"
  when: custom_list is defined

# Sets the variable to blank if the variable is not defined
- set_fact:
    custom_list: "{{ custom_list | default([]) }}"
  when: custom_list is not defined

# Concatenate the two lists together
- set_fact:
     main_list: "{{ default_list + custom_list }}"

#######################
# EMAIL USERS
#######################

- name: Sending an emails out to a list
  mail:
    #example mailserver
    host: smtp.example.com
    port: 587

    #ALERT@example.com
    username: ALERT@example.com
    password: "{{ vault_example_secret }}"

    #Sends emails to the IT administrators
    from: admin@example.com
    to: "{{ main_list }}"

    #Copies the template file and pastes it to the body of the email
    subject: Ansible report for {{ ansible_hostname }}
    body: "{{lookup('template','./templates/mail_template.txt')}}"
  delegate_to: localhost
