---
# Clears old/custom firewall rules
- name: flush ALL IP rules
  file:
    path: /etc/firewalld/zones
    state: absent

- name: restart firewalld service
  systemd:
    name: firewalld
    state: restarted

# example whitelist
- name: Firewalld example WHITELIST
  firewalld:
    zone: internal
    source: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 192.168.11.0/24
    - 192.168.20.X

# Blocks all other connections
- name: firewalld block all other connections
  firewalld:
    zone: public
    service: ssh
    permanent: yes
    immediate: yes
    state: disabled
