---
# Delete old files
- name: SSHD clearing old configurations
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - path: /etc/hosts.allow
    - path: /etc/hosts.deny

# Create blank files
- name: SSHD creating blank configuration files
  file:
    path: "{{ item.path }}"
    state: touch
  with_items:
    - path: /etc/hosts.allow
    - path: /etc/hosts.deny

# Copies template formatting to remote files
- name: SSHD populating "/etc/hosts.allow" from template
  template:
    src: ./templates/hosts.allow
    dest: /etc/hosts.allow

- name: SSHD populating "/etc/hosts.deny" from template
  template:
    src: ./templates/hosts.deny
    dest: /etc/hosts.deny

# Restart service to apply changes
- name: SSHD restart service
  service:
    name: sshd
    state: restarted

- name: SSH restart service
  service:
    name: ssh
    state: restarted

