---
# Gets a list of packages to be installed
- name: Gets a list of pending packages
  shell: yum check-update
  args:
    warn: false
  ignore_errors: yes
  register: package_simulate

# Removes un-needed dependency and upgrades package
- name: yum -y autoremove
  yum:
    autoremove: yes

- name: yum -y update
  yum:
    name: '*'
    state: latest
    update_cache: yes
  register: update

# Re-sync with RedHat Errata
- name: Remove old packages.json file
  file:
    path: /var/lib/rhsm/packages/packages.json
    state: absent

- name: Stop rhsmcertd service
  service:
    name: rhsmcertd
    state: stopped

- name: Start rhsmcertd service
  shell: rhsmcertd --now

# Restart required?
- name: check if reboot is needed
  stat:
    path: /var/run/reboot-required
  register: check_reboot
  
# Calculates restart time IF required
- name: get time
  set_fact:
    reboot_required: "'Yes'"
    restart_msg: "this machine will resart at "
    hour: "{{ ansible_date_time.hour | int + 1 }}"
    minute: "{{ ansible_date_time.minute }}"
    second: "{{ ansible_date_time.second }}"
  when: check_reboot.stat.exists
  
- name: set time
  set_fact:
    time: '{{ hour }}:{{ minute }}:{{ second }}'
  when: check_reboot.stat.exists
  
# Email IF there was an update - UNCOMMENT TO ENABLE
#- include: ./tasks/mail.yml
#  when: update.changed

# Ends playbook if file DOES NOT exist
- meta: end_host
  when: not check_reboot.stat.exists

# Schedule remote system reboot
- name: reboot system
  reboot:
    msg: "Reboot initiated by Ansible due to system updates"
    pre_reboot_delay: 3600
    post_reboot_delay: 300
    reboot_timeout: 5400
