---
################################################################################################################
#This playbook goes through all the current compliance checks and alerts the system administrator if there is an issue
#
#Last updated by: Ben Firestine 10/19/2020
################################################################################################################

# Filter out offline hosts
- name: identify reachable hosts
  hosts: all
  gather_facts: false

  # Required for computer_checked variable
  vars_files:
    - ./vars/default.yml

# Checking for online hosts
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for_connection:
            timeout: 5
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "reachable" group
          group_by:
            key: "reachable"
        # Metric for use in email
        - name: add the host to the computers_checked variable
          set_fact:
            computers_checked: "{{ computers_checked | int + 1 }}"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

# Compliance modules
- name: Online hosts
  hosts: reachable
  become: true
  any_errors_fatal: true
  gather_facts: True

# Import variable/secret files 
  vars_files:   
    - ../secrets/vault
    - ./vars/default.yml

  tasks:
  
  # Runs complaince modules and reporting
  - include: ./tasks/initial_setup.yml

  # Email resulting report - UNCOMMENT TO ENABLE
  #- include: ./tasks/mail.yml

  # Cleanup
  - name: Deleting excel file that was sent via email
    file:
      path: "{{ excel_loc }}"
      state: absent
    delegate_to: localhost
