---
#####################################################################################
# This playbook goes through all the current compliance checks and alerts the system Administrator if there is any issues
#
#Last updated by: Ben Firestine 06/23/2021
#####################################################################################

# Filter out offline hosts
- name: identify reachable hosts
  hosts: all
  gather_facts: false

  vars_files:
    - ./vars/default.yml

# Checking for online hosts
  tasks:
    - block:
        - name: determine hosts that are up
          wait_for:
            port: "{{ ssh_port }}"
          vars:
            ansible_connection: ssh
        - name: add devices with connectivity to the "reachable" group
          group_by:
            key: "reachable"
        # Metric for use in email
        - name: add the host to the computers_checked variable
          set_fact:
            computers_checked: "{{ computers_checked | int + 1 }}"
      rescue:
        - debug: msg="cannot connect to {{inventory_hostname}}"

# Compliance Modules
- name: Online hosts
  hosts: reachable
  become: true
  any_errors_fatal: true
  gather_facts: True

# Import variable/secret files 
  vars_files:   
   # - ../secrets/vault
    - ./vars/default.yml

  tasks:
  
  # Runs complaince modules and reporting
  - include: ./tasks/initial_setup.yml

  # Email resulting report. UNCOMMENT OUT TO ENABLE MAIL FUNCTION
  #- include: ./tasks/mail.yml

  # Cleanup
  - name: Deleting excel file that was sent via email
    file:
      path: "{{ excel_loc }}"
      state: absent
    delegate_to: localhost
